### ISSUE TITLE
Okay, this would be way awesome:  Ctrl+W

### ISSUE THREAD

**Issue by superscript18** [NickTomlin/pocketvim#7]
JSFiddle's different editor panes are arranged reminiscent of Vim's windows.  So it would be just *dreamy* if we could use the Ctrl+W keybindings to switch between them.

Any chance?

**Comment by superscript18** [comment]
Code-wise this could be super complicated, but we could simplify by just ignoring the cursor position and I don't think JSFiddle's panes are rearrangable.  Something should be able to be figured out that was generic and simple and sufficiently awesome.

Anyway, is this totally outside your scope or would a PR be appreciated?

**Comment by NickTomlin** [comment]
Interesting! Ideally pocketvim should be as light touch as possible, just setting up the bindings and letting them do their work, so i'm hesitant to try and add a feature like this since it require adding a key binding to Ace/Codemirror when we hook into it.. It could work if there's a simple univeralish way to decide which windows to switch to (maybe just look for instances of CodeMirror or Ace on the page?). What do you think?

Also, JSFiddle actually has vim support built in now, so you don't even need pocket vim!

![screen shot 2016-01-12 at 9 38 01 pm](https://cloud.githubusercontent.com/assets/1290336/12284363/c512bc9c-b974-11e5-99a1-61ac32e7a200.png)

**Comment by superscript18** [comment]
Hey neat, I guess I missed that key map option.

And yea, I don't know exactly how to do the layout switching universally.
I think it would look something like finding the editor instances and
comparing their bounding rectangles.  Also, in order not to break with
dynamic (rearrangable) window features, figuring the geometry might be best
when you hit Ctrl+W rather than on load.

Anyway, I haven't really got into your code, but I will take a look and see
if I can find an unobtrusive way to go about it.

Keep it up!

**Comment by NickTomlin** [comment]
Awesome. Thanks! I'm going to go ahead and close this for now. Feel free to re-open or submit a PR when you've taken a look.
